### ISSUE TITLE
Release community.rabbitmq collection v1.2.3

### ISSUE THREAD

**Issue by Im0** [ansible-collections/community.rabbitmq#143]
##### SUMMARY

Just a placeholder/reminder to package/release v1.2.3

##### ISSUE TYPE
- Release planning

##### COMPONENT NAME

community.rabbitmq

##### ADDITIONAL INFORMATION

Planning to include:
* #140   (#138)
* #141 
* #142 (#123)
* #139 
* #144 ( #114 )

Possibly:
* #120

**Comment by Im0** [comment]
Release PR #147

**Comment by Im0** [comment]
Released on galaxy and newsbot informed: 
```
newsbot[m]: collection.rabbitmq has released version 1.2.3 which available on github and galaxy.  More details are available within the [changelog](https://github.com/ansible-collections/community.rabbitmq/blob/main/CHANGELOG.rst).
```

**Comment by nrukavkov** [comment]
The feature was released?

**Comment by Im0** [comment]
> The feature was released?

Which feature are you specifically talking about?

**Comment by nrukavkov** [comment]
> * Add an option to allow rabbitmq_user to use API for managing users #120

https://github.com/ansible-collections/community.rabbitmq/pull/120

**Comment by Im0** [comment]
> > * Add an option to allow rabbitmq_user to use API for managing users [Add an option to allow rabbitmq_user to use API for managing users #120](https://github.com/ansible-collections/community.rabbitmq/pull/120)
> 
> #120

Sorry, it didn't make it as I didn't hear back from the authors in time.
