### ISSUE TITLE
Unmaintained collection: Removal from Ansible (community) package

### ISSUE THREAD

**Issue by mariolenz** [ansible-collections/community.rabbitmq#164]
It looks like this collection is effectively unmaintained. According to the current [community guidelines for collections](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#unmaintained-collections), we will consider removing it in a future version of the Ansible community package. Please see [Unmaintained collection: community.rabbitmq](https://forum.ansible.com/t/3931) for more information.

At least one month after this announcement appears here and on [Bullhorn](https://forum.ansible.com/c/news/bullhorn/17), the Ansible Community Steering Committee will vote on whether this collection is considered unmaintained and will be removed, or whether it will be kept. If it will be removed, this will happen earliest in Ansible 11. Please note that people can still manually install the collection with `ansible-galaxy collection install community.rabbitmq` even when it has been removed from Ansible.

**Comment by felixfontein** [comment]
Since this is a community collection, and some users (both maintainers and drive-by contributors) are still quite interested in this, I think it would be great if instead of being removed it could get a bit more active!

@g0tmi1k @csmart you recently (in the last half a year) merged PRs, so it seems there are still folks around with commit rights. Do you need more help? Do you still have time/interest to work on this?

**Comment by mariolenz** [comment]
@felixfontein Yes, this is a little bit weird... people seem to be working on this collection but there are no releases. I don't understand this :shrug:

At the end of the day, just fixing / improving things in the repo but not releasing is a problem IMHO...

**Comment by csmart** [comment]
I can find some more time to work on this and pick up on the releases... IMO let's not remove it yet and see how we go.

**Comment by mariolenz** [comment]
> IMO let's not remove it yet and see how we go.

@csmart Just to make this clear, it's not a question of removing the collection yet / now. Even _if_ we would decide to remove it, it would be comparatively easy to [cancel the removal](https://github.com/ansible-collections/overview/blob/main/removal_from_ansible.rst#cancelling-removal-of-an-unmaintained-collection) as long as Ansible 11 hasn't been released yet. And I guess this will be somewhere in November.

BTW if you do find the time to work on a new release, maybe you should consider making it a major one (2.0.0) and drop support for some older / [EOL](https://docs.ansible.com/ansible/9/reference_appendices/release_and_maintenance.html#ansible-core-support-matrix) versions of ansible-core as I've suggested in #162. It's not a requirement, but it might make you life easier. If nothing else, it would speed up the CI pipeline and save resources.

**Comment by csmart** [comment]
FYI, version `1.3.0` has been release which includes bug fixes and new feature to manage users via the API.

**Comment by mariolenz** [comment]
Thank you very much @csmart!
