### ISSUE TITLE
Add automated collection publishing

### ISSUE THREAD

**Issue by odyssey4me** [ansible-collections/community.rabbitmq#21]
##### SUMMARY

We should automate the publishing of a collection to ansible galaxy.

##### ISSUE TYPE
- Feature Idea

##### ADDITIONAL INFORMATION

```yaml

```

**Comment by Andersson007** [comment]
@odyssey4me hi, is this relevant? Doesn't Zuul publish the collection on Galaxy seeing new tags?

**Comment by odyssey4me** [comment]
Ah, yes it does. I guess we can close this. This was written well before any of that infrastructure existed.
