### ISSUE TITLE
[rabbitmq_user] permissions: with multiple vhosts breaks functionality in 2.7.2

### ISSUE THREAD

**Issue by NielsH** [ansible-collections/community.rabbitmq#34]
> Thank you very much for your interest in Ansible. This plugin is no longer maintained in this repository and has been migrated to https://github.com/ansible-collections/community.rabbitmq
> 
> Please re-submit this issue in the above repository.
> 
> If you have further questions please stop by IRC or the mailing list:
> 
> * IRC: #ansible on irc.freenode.net
> * mailing list: https://groups.google.com/forum/#!forum/ansible-project

See: https://github.com/ansible/ansible/issues/48890

It's really hard for me to comprehend how this issue can be open for 2 years with pull requests that fix it, people occasionally pinging for an update and now the old issue just gets closed with "reopen it in this other repo"... Is it gonna sit here as well now for 2 years? Very frustrating 😠 

Can we get this fixed/merged...?

**Comment by CSimpiFoN** [comment]
Yes, please. This is a very important feature. It should be merge as soon as possible. Thanks

**Comment by hozn** [comment]
Yeah, this is crazy.  I've run into this today and made the local 1-line fix .... but obviously that means that the playbooks only work from my machine.

**Comment by odyssey4me** [comment]
If you propose a PR, then it can get reviewed/tested here and merged pretty quickly.

**Comment by CSimpiFoN** [comment]
Like this one?
https://github.com/ansible/ansible/issues/48890

**Comment by JJCella** [comment]
Fixed with #36 

See [Filter out headers](https://github.com/ansible-collections/community.rabbitmq/commit/3c64fa61cc35cef05a8dd8456b9b85956c664f41#diff-6bbdd959b8dc318db56c749d27f66192R317)

**Comment by odyssey4me** [comment]
Closing now that the fix is released. Thanks!
