### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by francoisfreitag** [ansible-collections/community.rabbitmq#60]
The master branch contains several commits. At least https://github.com/ansible-collections/community.rabbitmq/commit/351d9fb11c09bc3f8f32992679c948a253226032 should fix https://github.com/ansible-collections/community.rabbitmq/issues/47.

##### SUMMARY
Can the current master branch be released so that users benefit from the fixes?

**Comment by odyssey4me** [comment]
https://github.com/ansible-collections/community.rabbitmq/releases/tag/1.0.2 is done, although it's not yet got to galaxy yet. I'll keep this open until that's complete. It's an automatic process, FYI.

**Comment by francoisfreitag** [comment]
Great, thank you!

**Comment by odyssey4me** [comment]
There was a problem with 1.0.2 for some reason, so I've tagged 1.0.3 which has finally been published. Thank you for your patience!
